### ISSUE TITLE
Давай сделаем без переменной x

### ISSUE THREAD

**Issue by tolstoymv** [AleksandrKerov/Homework2#3]
https://github.com/AleksandrKerov/Homework2/blob/3e0149f8f542a2f1054db66a42bc7e4786885f57/src/Massive.java#L16

Короче у тебя последовательность можно рассматривать как арифметическую прогрессию (как ты сделал) где на каждом шаге надо прибавить 3 к предыдущему. Это рабочая модель, но проще представлять по другому.

Как ты знаешь для арифметической прогрессии можно посчитать любой элемент по номеру не смотря на предыдущие.

Каждый элемент массива - это индекс умноженный на три.
0 1 2 3
0 3 6 9

То есть ты можешь для каждого индекса i писать что значение array[i] это i * 3

**Comment by AleksandrKerov** [comment]
Переделал без лишних переменных
