### ISSUE TITLE
В задании сказано что нужно заполнить массив значениями 

### ISSUE THREAD

**Issue by tolstoymv** [AleksandrKerov/Homework2#4]
https://github.com/AleksandrKerov/Homework2/blob/3e0149f8f542a2f1054db66a42bc7e4786885f57/src/Massive.java#L20

Саш, ты не обновил массив - ты напечатал числа - но сам массив остался заполненным нулями - нужно писать taskTwo[i] = новое значение

**Comment by AleksandrKerov** [comment]
Это вроде исправлено предыдущими изменениями, когда убрал переменную Х
