### ISSUE TITLE
Массив не обновляется

### ISSUE THREAD

**Issue by tolstoymv** [AleksandrKerov/Homework2#5]
https://github.com/AleksandrKerov/Homework2/blob/3e0149f8f542a2f1054db66a42bc7e4786885f57/src/Massive.java#L28

Ну тут задание написано хреново конечно - но в общем скорее всего надо или массив обновлять или новый создавать. В 99 случаях - пройтись по массиву и сделать что-то с элементами означает именно это.

А ты массив не меняешь просто достаешь элементы и печатаешь умноженные или нет

**Comment by AleksandrKerov** [comment]
Опять же поменял запись цикла. Теперь правильно?
