### ISSUE TITLE
3 как размер массива сделать отдельной переменной

### ISSUE THREAD

**Issue by tolstoymv** [AleksandrKerov/Homework2#7]
https://github.com/AleksandrKerov/Homework2/blob/3e0149f8f542a2f1054db66a42bc7e4786885f57/src/Massive.java#L35

int SIZE = 3 

int[][] array = int[SIZE][SIZE]
for(... < SIZE...)
...

**Comment by AleksandrKerov** [comment]
Вот это круто... Код в разы стал лучше)
