### ISSUE TITLE
Решение рабочее но унылое

### ISSUE THREAD

**Issue by tolstoymv** [AleksandrKerov/Homework2#9]
https://github.com/AleksandrKerov/Homework2/blob/3e0149f8f542a2f1054db66a42bc7e4786885f57/src/Massive.java#L78

В текущем варианте рябит в глазах от однобуквенных переменных и главное от выражений в индексах - array[smth - smthElse * j + z -y] - это очень не очень
Рекомендую сперва завести переменную в которую посчитать новый индекс (с именем понятным) и затем уже ее пихать в квадратные скобки.
Код должен читаться как газета. Без особых запинок с минимальным удержанием контекста в голове.

Но вообще говоря можно тупо проще решение сделать - сейчас ты идешь слева и на каждом шаге считаешь сумму справа. Это сложно - ты раз за разом пересчитываешь одно и тоже на самом деле.
Я предлагаю сперва посчитать всю сумму массива, а затем идти слева и считать пока не получится ровно половина.

Если было меньше половины а при добавлении элемента стало больше половины - то это сразу и точно провал - можно дальше не считать.

Для сравнения. Пусть массив в 1000 элементов 
если там нет места в котором суммы равны то твое решение сделает порядка 1 000 000 действий
А то которое я предлагаю порядка 1500 :)

**Comment by AleksandrKerov** [comment]
Не скажу, что прямо сходу врубился и за 5 сек все написал) Но по количеству операций твой способ явно выигрывает) Так что добил и переделал)
